// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	ID              int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt       time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_orders_deleted_at,priority:1" json:"deleted_at"`
	OrderSn         string         `gorm:"column:order_sn;type:varchar(64);uniqueIndex:idx_orders_order_sn,priority:1;comment:订单编号" json:"order_sn"` // 订单编号
	UserID          int64          `gorm:"column:user_id;type:bigint unsigned;index:idx_orders_user_id,priority:1;comment:用户ID" json:"user_id"`      // 用户ID
	Status          int32          `gorm:"column:status;type:int;default:1;comment:订单状态:1待支付,2待发货,3待收货,4已完成,5已取消" json:"status"`                     // 订单状态:1待支付,2待发货,3待收货,4已完成,5已取消
	TotalAmount     float64        `gorm:"column:total_amount;type:decimal(10,2);comment:订单总额" json:"total_amount"`                                  // 订单总额
	PayAmount       float64        `gorm:"column:pay_amount;type:decimal(10,2);comment:应付金额" json:"pay_amount"`                                      // 应付金额
	FreightAmount   float64        `gorm:"column:freight_amount;type:decimal(10,2);comment:运费" json:"freight_amount"`                                // 运费
	ReceiverName    string         `gorm:"column:receiver_name;type:varchar(64);comment:收货人" json:"receiver_name"`                                   // 收货人
	ReceiverPhone   string         `gorm:"column:receiver_phone;type:varchar(32);comment:联系电话" json:"receiver_phone"`                                // 联系电话
	ReceiverAddress string         `gorm:"column:receiver_address;type:varchar(512);comment:详细地址" json:"receiver_address"`                           // 详细地址
	Remark          string         `gorm:"column:remark;type:varchar(255);comment:备注" json:"remark"`                                                 // 备注
	PayTime         time.Time      `gorm:"column:pay_time;type:datetime(3);comment:支付时间" json:"pay_time"`                                            // 支付时间
	OrderItems      []OrderItem    `gorm:"foreignKey:OrderId" json:"order_items"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
