// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt     time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	OrderSn       string         `gorm:"size:64;uniqueIndex;comment:订单编号"`
	UserID        uint           `gorm:"index;comment:用户ID"`
	Status        int32          `gorm:"default:1;comment:订单状态:1待支付,2待发货,3待收货,4已完成,5已取消"`
	TotalAmount   float64        `gorm:"type:decimal(10,2);comment:订单总额"`
	PayAmount     float64        `gorm:"type:decimal(10,2);comment:应付金额"`
	FreightAmount float64        `gorm:"type:decimal(10,2);comment:运费"`

	// 收货人信息（快照，防止地址簿修改影响历史订单）
	ReceiverName    string `gorm:"size:64;comment:收货人"`
	ReceiverPhone   string `gorm:"size:32;comment:联系电话"`
	ReceiverAddress string `gorm:"size:512;comment:详细地址"`

	Remark  string     `gorm:"size:255;comment:备注"`
	PayTime *time.Time `gorm:"comment:支付时间"`

	// 关联订单项
	OrderItems []OrderItem `gorm:"foreignKey:OrderId"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
