// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrderItem = "order_items"

// OrderItem mapped from table <order_items>
type OrderItem struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	OrderID   uint           `gorm:"index;comment:订单ID"`
	OrderSn   string         `gorm:"size:64;index;comment:订单编号"`
	SpuID     uint           `gorm:"comment:商品SPU_ID"`
	SkuID     uint           `gorm:"comment:商品SKU_ID"`
	SkuName   string         `gorm:"size:255;comment:商品名称"`
	SkuPic    string         `gorm:"size:512;comment:商品图片"`
	Price     float64        `gorm:"type:decimal(10,2);comment:下单时价格"`
	Num       int32          `gorm:"comment:购买数量"`
}

// TableName OrderItem's table name
func (*OrderItem) TableName() string {
	return TableNameOrderItem
}
