// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrderItem = "order_items"

// OrderItem mapped from table <order_items>
type OrderItem struct {
	ID        int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_order_items_deleted_at,priority:1" json:"deleted_at"`
	OrderID   int64          `gorm:"column:order_id;type:bigint unsigned;index:idx_order_items_order_id,priority:1;comment:订单ID" json:"order_id"` // 订单ID
	OrderSn   string         `gorm:"column:order_sn;type:varchar(64);index:idx_order_items_order_sn,priority:1;comment:订单编号" json:"order_sn"`     // 订单编号
	SpuID     int64          `gorm:"column:spu_id;type:bigint unsigned;comment:商品SPU_ID" json:"spu_id"`                                           // 商品SPU_ID
	SkuID     int64          `gorm:"column:sku_id;type:bigint unsigned;comment:商品SKU_ID" json:"sku_id"`                                           // 商品SKU_ID
	SkuName   string         `gorm:"column:sku_name;type:varchar(255);comment:商品名称" json:"sku_name"`                                              // 商品名称
	SkuPic    string         `gorm:"column:sku_pic;type:varchar(512);comment:商品图片" json:"sku_pic"`                                                // 商品图片
	Price     float64        `gorm:"column:price;type:decimal(10,2);comment:下单时价格" json:"price"`                                                  // 下单时价格
	Num       int32          `gorm:"column:num;type:int;comment:购买数量" json:"num"`                                                                 // 购买数量
}

// TableName OrderItem's table name
func (*OrderItem) TableName() string {
	return TableNameOrderItem
}
