// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProductSku = "product_skus"

// ProductSku mapped from table <product_skus>
type ProductSku struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	SpuID     int64          `gorm:"column:spu_id;comment:所属SPU_ID" json:"spu_id"`         // 所属SPU_ID
	SkuCode   string         `gorm:"column:sku_code;comment:SKU唯一编码" json:"sku_code"`      // SKU唯一编码
	AttrValue string         `gorm:"column:attr_value;comment:属性组合JSON" json:"attr_value"` // 属性组合JSON
	Price     float64        `gorm:"column:price;comment:售价" json:"price"`                 // 售价
	Stock     int64          `gorm:"column:stock;comment:库存数量" json:"stock"`               // 库存数量
}

// TableName ProductSku's table name
func (*ProductSku) TableName() string {
	return TableNameProductSku
}
