// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProductSpu = "product_spus"

// ProductSpu mapped from table <product_spus>
type ProductSpu struct {
	ID          int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_product_spus_deleted_at,priority:1" json:"deleted_at"`
	Name        string         `gorm:"column:name;type:varchar(255);not null;comment:商品名称" json:"name"`                                                       // 商品名称
	Description string         `gorm:"column:description;type:text;comment:商品详情介绍" json:"description"`                                                        // 商品详情介绍
	CategoryID  int64          `gorm:"column:category_id;type:bigint unsigned;index:idx_product_spus_category_id,priority:1;comment:分类ID" json:"category_id"` // 分类ID
	BrandID     int64          `gorm:"column:brand_id;type:bigint unsigned;index:idx_product_spus_brand_id,priority:1;comment:品牌ID" json:"brand_id"`          // 品牌ID
	MainImage   string         `gorm:"column:main_image;type:varchar(512);comment:主图URL" json:"main_image"`                                                   // 主图URL
	IsOnSale    bool           `gorm:"column:is_on_sale;type:tinyint(1);comment:是否上架" json:"is_on_sale"`                                                      // 是否上架
	Skus        []ProductSku   `gorm:"foreignKey:SpuId" json:"skus"`
}

// TableName ProductSpu's table name
func (*ProductSpu) TableName() string {
	return TableNameProductSpu
}
