// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProductSpu = "product_spus"

// ProductSpu mapped from table <product_spus>
type ProductSpu struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Name        string         `gorm:"column:name;size:255;not null;comment:商品名称"`
	Description string         `gorm:"column:description;type:text;comment:商品详情介绍"`
	CategoryID  uint           `gorm:"column:category_id;index;comment:分类ID"`
	BrandID     uint           `gorm:"column:brand_id;index;comment:品牌ID"`
	MainImage   string         `gorm:"column:main_image;size:512;comment:主图URL"`
	IsOnSale    bool           `gorm:"column:is_on_sale;default:false;comment:是否上架"`
	// 一对多关系：一个 SPU 对应多个 SKU
	Skus []ProductSku `gorm:"foreignKey:SpuId" json:"skus"`
}

// TableName ProductSpu's table name
func (*ProductSpu) TableName() string {
	return TableNameProductSpu
}
