// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProductSpu = "product_spus"

// ProductSpu mapped from table <product_spus>
type ProductSpu struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Name        string         `gorm:"column:name;not null;comment:商品名称" json:"name"`        // 商品名称
	Description string         `gorm:"column:description;comment:商品详情介绍" json:"description"` // 商品详情介绍
	CategoryID  int64          `gorm:"column:category_id;comment:分类ID" json:"category_id"`   // 分类ID
	BrandID     int64          `gorm:"column:brand_id;comment:品牌ID" json:"brand_id"`         // 品牌ID
	MainImage   string         `gorm:"column:main_image;comment:主图URL" json:"main_image"`    // 主图URL
	IsOnSale    bool           `gorm:"column:is_on_sale;comment:是否上架" json:"is_on_sale"`     // 是否上架
	Skus        []ProductSku   `json:"skus"`
}

// TableName ProductSpu's table name
func (*ProductSpu) TableName() string {
	return TableNameProductSpu
}
