// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	ID        int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Code      string     `gorm:"column:code;type:varchar(32);index:code,priority:1" json:"code"`
	Name      string     `gorm:"column:name;type:varchar(64)" json:"name"`
	UserRoles []UserRole `gorm:"foreignKey:RoleID" json:"user_roles"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
