// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserRole = "user_roles"

// UserRole mapped from table <user_roles>
type UserRole struct {
	ID     int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	UserID int32  `gorm:"column:user_id;type:int;index:fk_users_user_roles,priority:1" json:"user_id"`
	RoleID int32  `gorm:"column:role_id;type:int;index:fk_user_roles_role,priority:1" json:"role_id"`
	Status string `gorm:"column:status;type:varchar(8)" json:"status"`
	User   User   `json:"user"`
	Role   Role   `json:"role"`
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
