// api/user.proto
syntax = "proto3";

package user.v1;

import "validate/validate.proto";
import "google/api/annotations.proto";


option go_package = "gin-krotas-gorm/api/user/v1;v1";
option java_multiple_files = true;
option java_package = "dev.kratos.api.user.v1";
option java_outer_classname = "UserProtoV1";

service User {
  rpc Register (RegisterRequest) returns (UserReply) {
    option (google.api.http) = {
      post: "/v1/users"
      body: "*"
    };
  }

  rpc GetByID (SingleIDRequest) returns (UserReply) {
    option (google.api.http) = {
      get: "/v1/users/{id}"
    };
  }

  rpc UpdateRoleByID (UpdateRoleRequest) returns (SimpleResponse) {
    option (google.api.http) = {
      put: "/v1/users/{id}/role"
      body: "*"
    };
  }
  rpc Login (LoginRequest) returns (UserReply) {
    option (google.api.http) = {
      post: "/v1/users/login"
      body: "*"
    };
  }
}

message LoginRequest {
  string name = 1;
  string password = 2;
}

message RegisterRequest {
  string name = 1;
}

message SingleIDRequest {
  uint64 id = 1;
}

message UpdateRoleRequest {
  uint64 id = 1;
  repeated uint64 role_id = 2 [(validate.rules).repeated.min_items = 1];
}

message SimpleResponse {
  string msg = 1;
}

message UserReply {
  uint64 id = 1;
  string name = 2;
  repeated uint64 role_id = 3;
}