// api/user.proto
syntax = "proto3";

package user.v1;

import "google/api/annotations.proto";

option go_package = "helloworld-go/api/user/v1;v1";
option java_multiple_files = true;
option java_package = "dev.kratos.api.user.v1";
option java_outer_classname = "UserProtoV1";

service UserService {
  rpc Register (RegisterRequest) returns (UserReply);
  rpc GetByID (GetByIDRequest) returns (UserReply);
}

message RegisterRequest {
  string name = 1;
}

message GetByIDRequest {
  int64 id = 1;
}

message UserReply {
  int64 id = 1;
  string name = 2;
}
