// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStockLog = "stock_logs"

// StockLog mapped from table <stock_logs>
type StockLog struct {
	ID    string `gorm:"column:id;type:varchar(64);primaryKey;comment:幂等ID，通常使用订单号" json:"id"` // 幂等ID，通常使用订单号
	SkuID int64  `gorm:"column:sku_id;type:bigint;not null" json:"sku_id"`
	Num   int32  `gorm:"column:num;type:int;not null" json:"num"`
}

// TableName StockLog's table name
func (*StockLog) TableName() string {
	return TableNameStockLog
}
