server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(10.211.55.29:3306)/unicorn?parseTime=True&loc=Local
  redis:
    addr: 10.211.55.29:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  # 新增 DTM 配置
  dtm:
    address: "discovery:///dtmservice" # DTM Server 的 gRPC 地址
    timeout: 5s
registry:
  etcd:
    endpoints:
      - 10.211.55.29:2379