// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q          = new(Query)
	ProductSku *productSku
	ProductSpu *productSpu
	StockLog   *stockLog
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	ProductSku = &Q.ProductSku
	ProductSpu = &Q.ProductSpu
	StockLog = &Q.StockLog
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:         db,
		ProductSku: newProductSku(db, opts...),
		ProductSpu: newProductSpu(db, opts...),
		StockLog:   newStockLog(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ProductSku productSku
	ProductSpu productSpu
	StockLog   stockLog
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:         db,
		ProductSku: q.ProductSku.clone(db),
		ProductSpu: q.ProductSpu.clone(db),
		StockLog:   q.StockLog.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:         db,
		ProductSku: q.ProductSku.replaceDB(db),
		ProductSpu: q.ProductSpu.replaceDB(db),
		StockLog:   q.StockLog.replaceDB(db),
	}
}

type queryCtx struct {
	ProductSku IProductSkuDo
	ProductSpu IProductSpuDo
	StockLog   IStockLogDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ProductSku: q.ProductSku.WithContext(ctx),
		ProductSpu: q.ProductSpu.WithContext(ctx),
		StockLog:   q.StockLog.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
