// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package product

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"helloworld-go/internal/biz/model"
)

func newProductSku(db *gorm.DB, opts ...gen.DOOption) productSku {
	_productSku := productSku{}

	_productSku.productSkuDo.UseDB(db, opts...)
	_productSku.productSkuDo.UseModel(&model.ProductSku{})

	tableName := _productSku.productSkuDo.TableName()
	_productSku.ALL = field.NewAsterisk(tableName)
	_productSku.ID = field.NewInt64(tableName, "id")
	_productSku.CreatedAt = field.NewTime(tableName, "created_at")
	_productSku.UpdatedAt = field.NewTime(tableName, "updated_at")
	_productSku.DeletedAt = field.NewField(tableName, "deleted_at")
	_productSku.SpuID = field.NewInt64(tableName, "spu_id")
	_productSku.SkuCode = field.NewString(tableName, "sku_code")
	_productSku.AttrValue = field.NewString(tableName, "attr_value")
	_productSku.Price = field.NewFloat64(tableName, "price")
	_productSku.Stock = field.NewInt64(tableName, "stock")

	_productSku.fillFieldMap()

	return _productSku
}

type productSku struct {
	productSkuDo productSkuDo

	ALL       field.Asterisk
	ID        field.Int64
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	SpuID     field.Int64   // 所属SPU_ID
	SkuCode   field.String  // SKU唯一编码
	AttrValue field.String  // 属性组合JSON
	Price     field.Float64 // 售价
	Stock     field.Int64   // 库存数量

	fieldMap map[string]field.Expr
}

func (p productSku) Table(newTableName string) *productSku {
	p.productSkuDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productSku) As(alias string) *productSku {
	p.productSkuDo.DO = *(p.productSkuDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productSku) updateTableName(table string) *productSku {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.SpuID = field.NewInt64(table, "spu_id")
	p.SkuCode = field.NewString(table, "sku_code")
	p.AttrValue = field.NewString(table, "attr_value")
	p.Price = field.NewFloat64(table, "price")
	p.Stock = field.NewInt64(table, "stock")

	p.fillFieldMap()

	return p
}

func (p *productSku) WithContext(ctx context.Context) IProductSkuDo {
	return p.productSkuDo.WithContext(ctx)
}

func (p productSku) TableName() string { return p.productSkuDo.TableName() }

func (p productSku) Alias() string { return p.productSkuDo.Alias() }

func (p productSku) Columns(cols ...field.Expr) gen.Columns { return p.productSkuDo.Columns(cols...) }

func (p *productSku) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productSku) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["spu_id"] = p.SpuID
	p.fieldMap["sku_code"] = p.SkuCode
	p.fieldMap["attr_value"] = p.AttrValue
	p.fieldMap["price"] = p.Price
	p.fieldMap["stock"] = p.Stock
}

func (p productSku) clone(db *gorm.DB) productSku {
	p.productSkuDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productSku) replaceDB(db *gorm.DB) productSku {
	p.productSkuDo.ReplaceDB(db)
	return p
}

type productSkuDo struct{ gen.DO }

type IProductSkuDo interface {
	gen.SubQuery
	Debug() IProductSkuDo
	WithContext(ctx context.Context) IProductSkuDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProductSkuDo
	WriteDB() IProductSkuDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProductSkuDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProductSkuDo
	Not(conds ...gen.Condition) IProductSkuDo
	Or(conds ...gen.Condition) IProductSkuDo
	Select(conds ...field.Expr) IProductSkuDo
	Where(conds ...gen.Condition) IProductSkuDo
	Order(conds ...field.Expr) IProductSkuDo
	Distinct(cols ...field.Expr) IProductSkuDo
	Omit(cols ...field.Expr) IProductSkuDo
	Join(table schema.Tabler, on ...field.Expr) IProductSkuDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProductSkuDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProductSkuDo
	Group(cols ...field.Expr) IProductSkuDo
	Having(conds ...gen.Condition) IProductSkuDo
	Limit(limit int) IProductSkuDo
	Offset(offset int) IProductSkuDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProductSkuDo
	Unscoped() IProductSkuDo
	Create(values ...*model.ProductSku) error
	CreateInBatches(values []*model.ProductSku, batchSize int) error
	Save(values ...*model.ProductSku) error
	First() (*model.ProductSku, error)
	Take() (*model.ProductSku, error)
	Last() (*model.ProductSku, error)
	Find() ([]*model.ProductSku, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProductSku, err error)
	FindInBatches(result *[]*model.ProductSku, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ProductSku) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProductSkuDo
	Assign(attrs ...field.AssignExpr) IProductSkuDo
	Joins(fields ...field.RelationField) IProductSkuDo
	Preload(fields ...field.RelationField) IProductSkuDo
	FirstOrInit() (*model.ProductSku, error)
	FirstOrCreate() (*model.ProductSku, error)
	FindByPage(offset int, limit int) (result []*model.ProductSku, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProductSkuDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p productSkuDo) Debug() IProductSkuDo {
	return p.withDO(p.DO.Debug())
}

func (p productSkuDo) WithContext(ctx context.Context) IProductSkuDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productSkuDo) ReadDB() IProductSkuDo {
	return p.Clauses(dbresolver.Read)
}

func (p productSkuDo) WriteDB() IProductSkuDo {
	return p.Clauses(dbresolver.Write)
}

func (p productSkuDo) Session(config *gorm.Session) IProductSkuDo {
	return p.withDO(p.DO.Session(config))
}

func (p productSkuDo) Clauses(conds ...clause.Expression) IProductSkuDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productSkuDo) Returning(value interface{}, columns ...string) IProductSkuDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productSkuDo) Not(conds ...gen.Condition) IProductSkuDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productSkuDo) Or(conds ...gen.Condition) IProductSkuDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productSkuDo) Select(conds ...field.Expr) IProductSkuDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productSkuDo) Where(conds ...gen.Condition) IProductSkuDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productSkuDo) Order(conds ...field.Expr) IProductSkuDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productSkuDo) Distinct(cols ...field.Expr) IProductSkuDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productSkuDo) Omit(cols ...field.Expr) IProductSkuDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productSkuDo) Join(table schema.Tabler, on ...field.Expr) IProductSkuDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productSkuDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProductSkuDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productSkuDo) RightJoin(table schema.Tabler, on ...field.Expr) IProductSkuDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productSkuDo) Group(cols ...field.Expr) IProductSkuDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productSkuDo) Having(conds ...gen.Condition) IProductSkuDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productSkuDo) Limit(limit int) IProductSkuDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productSkuDo) Offset(offset int) IProductSkuDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productSkuDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProductSkuDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productSkuDo) Unscoped() IProductSkuDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productSkuDo) Create(values ...*model.ProductSku) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productSkuDo) CreateInBatches(values []*model.ProductSku, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productSkuDo) Save(values ...*model.ProductSku) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productSkuDo) First() (*model.ProductSku, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductSku), nil
	}
}

func (p productSkuDo) Take() (*model.ProductSku, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductSku), nil
	}
}

func (p productSkuDo) Last() (*model.ProductSku, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductSku), nil
	}
}

func (p productSkuDo) Find() ([]*model.ProductSku, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProductSku), err
}

func (p productSkuDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProductSku, err error) {
	buf := make([]*model.ProductSku, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productSkuDo) FindInBatches(result *[]*model.ProductSku, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productSkuDo) Attrs(attrs ...field.AssignExpr) IProductSkuDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productSkuDo) Assign(attrs ...field.AssignExpr) IProductSkuDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productSkuDo) Joins(fields ...field.RelationField) IProductSkuDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productSkuDo) Preload(fields ...field.RelationField) IProductSkuDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productSkuDo) FirstOrInit() (*model.ProductSku, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductSku), nil
	}
}

func (p productSkuDo) FirstOrCreate() (*model.ProductSku, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductSku), nil
	}
}

func (p productSkuDo) FindByPage(offset int, limit int) (result []*model.ProductSku, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productSkuDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productSkuDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productSkuDo) Delete(models ...*model.ProductSku) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productSkuDo) withDO(do gen.Dao) *productSkuDo {
	p.DO = *do.(*gen.DO)
	return p
}
