// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"helloworld-go/internal/biz/model"
)

func newProductSpu(db *gorm.DB, opts ...gen.DOOption) productSpu {
	_productSpu := productSpu{}

	_productSpu.productSpuDo.UseDB(db, opts...)
	_productSpu.productSpuDo.UseModel(&model.ProductSpu{})

	tableName := _productSpu.productSpuDo.TableName()
	_productSpu.ALL = field.NewAsterisk(tableName)
	_productSpu.ID = field.NewInt64(tableName, "id")
	_productSpu.CreatedAt = field.NewTime(tableName, "created_at")
	_productSpu.UpdatedAt = field.NewTime(tableName, "updated_at")
	_productSpu.DeletedAt = field.NewField(tableName, "deleted_at")
	_productSpu.Name = field.NewString(tableName, "name")
	_productSpu.Description = field.NewString(tableName, "description")
	_productSpu.CategoryID = field.NewInt64(tableName, "category_id")
	_productSpu.BrandID = field.NewInt64(tableName, "brand_id")
	_productSpu.MainImage = field.NewString(tableName, "main_image")
	_productSpu.IsOnSale = field.NewBool(tableName, "is_on_sale")
	_productSpu.Skus = productSpuHasManySkus{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Skus", "model.ProductSku"),
	}

	_productSpu.fillFieldMap()

	return _productSpu
}

type productSpu struct {
	productSpuDo productSpuDo

	ALL         field.Asterisk
	ID          field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	Name        field.String // 商品名称
	Description field.String // 商品详情介绍
	CategoryID  field.Int64  // 分类ID
	BrandID     field.Int64  // 品牌ID
	MainImage   field.String // 主图URL
	IsOnSale    field.Bool   // 是否上架
	Skus        productSpuHasManySkus

	fieldMap map[string]field.Expr
}

func (p productSpu) Table(newTableName string) *productSpu {
	p.productSpuDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productSpu) As(alias string) *productSpu {
	p.productSpuDo.DO = *(p.productSpuDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productSpu) updateTableName(table string) *productSpu {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.Name = field.NewString(table, "name")
	p.Description = field.NewString(table, "description")
	p.CategoryID = field.NewInt64(table, "category_id")
	p.BrandID = field.NewInt64(table, "brand_id")
	p.MainImage = field.NewString(table, "main_image")
	p.IsOnSale = field.NewBool(table, "is_on_sale")

	p.fillFieldMap()

	return p
}

func (p *productSpu) WithContext(ctx context.Context) IProductSpuDo {
	return p.productSpuDo.WithContext(ctx)
}

func (p productSpu) TableName() string { return p.productSpuDo.TableName() }

func (p productSpu) Alias() string { return p.productSpuDo.Alias() }

func (p productSpu) Columns(cols ...field.Expr) gen.Columns { return p.productSpuDo.Columns(cols...) }

func (p *productSpu) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productSpu) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 11)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["name"] = p.Name
	p.fieldMap["description"] = p.Description
	p.fieldMap["category_id"] = p.CategoryID
	p.fieldMap["brand_id"] = p.BrandID
	p.fieldMap["main_image"] = p.MainImage
	p.fieldMap["is_on_sale"] = p.IsOnSale

}

func (p productSpu) clone(db *gorm.DB) productSpu {
	p.productSpuDo.ReplaceConnPool(db.Statement.ConnPool)
	p.Skus.db = db.Session(&gorm.Session{Initialized: true})
	p.Skus.db.Statement.ConnPool = db.Statement.ConnPool
	return p
}

func (p productSpu) replaceDB(db *gorm.DB) productSpu {
	p.productSpuDo.ReplaceDB(db)
	p.Skus.db = db.Session(&gorm.Session{})
	return p
}

type productSpuHasManySkus struct {
	db *gorm.DB

	field.RelationField
}

func (a productSpuHasManySkus) Where(conds ...field.Expr) *productSpuHasManySkus {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a productSpuHasManySkus) WithContext(ctx context.Context) *productSpuHasManySkus {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a productSpuHasManySkus) Session(session *gorm.Session) *productSpuHasManySkus {
	a.db = a.db.Session(session)
	return &a
}

func (a productSpuHasManySkus) Model(m *model.ProductSpu) *productSpuHasManySkusTx {
	return &productSpuHasManySkusTx{a.db.Model(m).Association(a.Name())}
}

func (a productSpuHasManySkus) Unscoped() *productSpuHasManySkus {
	a.db = a.db.Unscoped()
	return &a
}

type productSpuHasManySkusTx struct{ tx *gorm.Association }

func (a productSpuHasManySkusTx) Find() (result []*model.ProductSku, err error) {
	return result, a.tx.Find(&result)
}

func (a productSpuHasManySkusTx) Append(values ...*model.ProductSku) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a productSpuHasManySkusTx) Replace(values ...*model.ProductSku) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a productSpuHasManySkusTx) Delete(values ...*model.ProductSku) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a productSpuHasManySkusTx) Clear() error {
	return a.tx.Clear()
}

func (a productSpuHasManySkusTx) Count() int64 {
	return a.tx.Count()
}

func (a productSpuHasManySkusTx) Unscoped() *productSpuHasManySkusTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type productSpuDo struct{ gen.DO }

type IProductSpuDo interface {
	gen.SubQuery
	Debug() IProductSpuDo
	WithContext(ctx context.Context) IProductSpuDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProductSpuDo
	WriteDB() IProductSpuDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProductSpuDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProductSpuDo
	Not(conds ...gen.Condition) IProductSpuDo
	Or(conds ...gen.Condition) IProductSpuDo
	Select(conds ...field.Expr) IProductSpuDo
	Where(conds ...gen.Condition) IProductSpuDo
	Order(conds ...field.Expr) IProductSpuDo
	Distinct(cols ...field.Expr) IProductSpuDo
	Omit(cols ...field.Expr) IProductSpuDo
	Join(table schema.Tabler, on ...field.Expr) IProductSpuDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProductSpuDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProductSpuDo
	Group(cols ...field.Expr) IProductSpuDo
	Having(conds ...gen.Condition) IProductSpuDo
	Limit(limit int) IProductSpuDo
	Offset(offset int) IProductSpuDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProductSpuDo
	Unscoped() IProductSpuDo
	Create(values ...*model.ProductSpu) error
	CreateInBatches(values []*model.ProductSpu, batchSize int) error
	Save(values ...*model.ProductSpu) error
	First() (*model.ProductSpu, error)
	Take() (*model.ProductSpu, error)
	Last() (*model.ProductSpu, error)
	Find() ([]*model.ProductSpu, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProductSpu, err error)
	FindInBatches(result *[]*model.ProductSpu, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ProductSpu) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProductSpuDo
	Assign(attrs ...field.AssignExpr) IProductSpuDo
	Joins(fields ...field.RelationField) IProductSpuDo
	Preload(fields ...field.RelationField) IProductSpuDo
	FirstOrInit() (*model.ProductSpu, error)
	FirstOrCreate() (*model.ProductSpu, error)
	FindByPage(offset int, limit int) (result []*model.ProductSpu, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProductSpuDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p productSpuDo) Debug() IProductSpuDo {
	return p.withDO(p.DO.Debug())
}

func (p productSpuDo) WithContext(ctx context.Context) IProductSpuDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productSpuDo) ReadDB() IProductSpuDo {
	return p.Clauses(dbresolver.Read)
}

func (p productSpuDo) WriteDB() IProductSpuDo {
	return p.Clauses(dbresolver.Write)
}

func (p productSpuDo) Session(config *gorm.Session) IProductSpuDo {
	return p.withDO(p.DO.Session(config))
}

func (p productSpuDo) Clauses(conds ...clause.Expression) IProductSpuDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productSpuDo) Returning(value interface{}, columns ...string) IProductSpuDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productSpuDo) Not(conds ...gen.Condition) IProductSpuDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productSpuDo) Or(conds ...gen.Condition) IProductSpuDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productSpuDo) Select(conds ...field.Expr) IProductSpuDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productSpuDo) Where(conds ...gen.Condition) IProductSpuDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productSpuDo) Order(conds ...field.Expr) IProductSpuDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productSpuDo) Distinct(cols ...field.Expr) IProductSpuDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productSpuDo) Omit(cols ...field.Expr) IProductSpuDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productSpuDo) Join(table schema.Tabler, on ...field.Expr) IProductSpuDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productSpuDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProductSpuDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productSpuDo) RightJoin(table schema.Tabler, on ...field.Expr) IProductSpuDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productSpuDo) Group(cols ...field.Expr) IProductSpuDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productSpuDo) Having(conds ...gen.Condition) IProductSpuDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productSpuDo) Limit(limit int) IProductSpuDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productSpuDo) Offset(offset int) IProductSpuDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productSpuDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProductSpuDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productSpuDo) Unscoped() IProductSpuDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productSpuDo) Create(values ...*model.ProductSpu) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productSpuDo) CreateInBatches(values []*model.ProductSpu, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productSpuDo) Save(values ...*model.ProductSpu) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productSpuDo) First() (*model.ProductSpu, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductSpu), nil
	}
}

func (p productSpuDo) Take() (*model.ProductSpu, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductSpu), nil
	}
}

func (p productSpuDo) Last() (*model.ProductSpu, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductSpu), nil
	}
}

func (p productSpuDo) Find() ([]*model.ProductSpu, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProductSpu), err
}

func (p productSpuDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProductSpu, err error) {
	buf := make([]*model.ProductSpu, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productSpuDo) FindInBatches(result *[]*model.ProductSpu, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productSpuDo) Attrs(attrs ...field.AssignExpr) IProductSpuDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productSpuDo) Assign(attrs ...field.AssignExpr) IProductSpuDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productSpuDo) Joins(fields ...field.RelationField) IProductSpuDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productSpuDo) Preload(fields ...field.RelationField) IProductSpuDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productSpuDo) FirstOrInit() (*model.ProductSpu, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductSpu), nil
	}
}

func (p productSpuDo) FirstOrCreate() (*model.ProductSpu, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductSpu), nil
	}
}

func (p productSpuDo) FindByPage(offset int, limit int) (result []*model.ProductSpu, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productSpuDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productSpuDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productSpuDo) Delete(models ...*model.ProductSpu) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productSpuDo) withDO(do gen.Dao) *productSpuDo {
	p.DO = *do.(*gen.DO)
	return p
}
